# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'Kata' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kata

  target 'KataTests' do
    inherit! :search_paths
    pod 'Cuckoo'
  end

#  target 'KataUITests' do
#    # Pods for testing
#  end

end
